#!/bin/sh

export RUBY_VERSION=2.1.6-github
export RBENV_VERSION=2.1.6-github
export PATH=/usr/share/rbenv/shims:/usr/sbin:$PATH
export BASE_DIR=/data/multibinder

REALPATH=$(cd $(dirname "$0") && pwd)
cd $REALPATH/../

bundle install --local --quiet --path vendor/gems
