#!/bin/sh

set -e

SHELL=/bin/sh

date "+%Y-%m-%dT%H:%M:%SZ"
echo "Beginning tests for Binder"
echo "==="

ls -1 test/test-*.sh | xargs -I % -n 1 ${SHELL} % --batch

echo "==="
date "+%Y-%m-%dT%H:%M:%SZ"
echo "Done."
